### ISSUE TITLE
Japanese not displayed properly in term page

### ISSUE THREAD

**Issue by elserj** [Planteome/amigo#1]
The Japanese synonyms show up properly on the main page (http://dev.planteome.org/amigo/search/ontology), but not on the term page (http://dev.planteome.org/amigo/term/PO:0025034).  They do show up properly if the user changes the encoding setting on their browser.

**Comment by kltm** [comment]
I've referenced this ticket as an upstream one in geneontology/amigo#260, and will take no further action here. I've tagged on @elserj upstream, so I suggest watching that one and re-merging after it's closed.

(BTW, as I'm not part of any team that has access privs to this repo, I cannot do things like close myself, which is fine, but FYI.)

(Also, for things that are affecting core issues, like text rendering, feel free to open tickets upstream; if we don't like them we'll close them and pass them back.)
