### ISSUE TITLE
AmiGO 2: Gene Product Details for Ensembl_Plants:AT4G38130

### ISSUE THREAD

**Issue by jaiswalp** [Planteome/amigo#10]
http://dev.planteome.org/amigo/gene_product/Ensembl_Plants:AT4G38130

please drop the go-ortholog file for A. thaliana from loading.

**Comment by elserj** [comment]
This was just a test load, I wasn't planning on loading it for the release.

But should I remove it from svn if we aren't going to use it?  That way I wouldn't have to manually remove it at release.

**Comment by jaiswalp** [comment]
On 1/3/2016 9:49 AM, elserj wrote:

> But should I remove it from svn if we aren't going to use it? That way I
> wouldn't have to manually remove it at release

yes.

## 

Pankaj Jaiswal, PhD
Associate Professor
Dept. of Botany and Plant Pathology
2082 Cordley Hall
Oregon State University
Corvallis, OR, 97331
USA

Ph.: +1-541-737-8471
Fax: +1-541-737-3573
email: jaiswalp@oregonstate.edu
Web: http://jaiswallab.cgrb.oregonstate.edu/
