### ISSUE TITLE
GR_gene Xref need fixing

### ISSUE THREAD

**Issue by jaiswalp** [Planteome/amigo#13]
http://dev.planteome.org/amigo/gene_product/GR_gene:60333

looked at http://palea.cgrb.oregonstate.edu/viewsvn/associations/to-associations/to_Gene_association.assoc?revision=679&view=markup

actual object_ID is 'GR:0060141'
If it is used as above the link to Gramene would work
like 

http://archive.gramene.org/db/genes/search_gene?acc=ID
e.g
http://archive.gramene.org/db/genes/search_gene?acc=GR:0060333

replacing ID with GR:0060333
The existing URL e.g. from this page http://dev.planteome.org/amigo/gene_product/GR_gene:60333 is missing the prefix 'GR:00' from the ID

**Comment by elserj** [comment]
Fixed by association svn commit 695.
