### ISSUE TITLE
putting search box on the homepage

### ISSUE THREAD

**Issue by jaiswalp** [Planteome/amigo#14]
is there a way to put the search box we see on the right hand side on http://browser.planteome.org/amigo/search/annotation on the www.Planteome.org homepage

**Comment by elserj** [comment]
I have a test one up at http://planteome.org/node/97.  Let me know if you like it or want anything changed.  I based it off the old one on plantontology.org.

@cooperl09 should check it out as well.

**Comment by elserj** [comment]
Pankaj, Lol and I tweaked the new search up at http://planteome.org/node/97.  Can you check it out and let us know if we should make it the homepage?

Thanks,
Justin

**Comment by jaiswalp** [comment]
Looking good. Do you think auto fill can be applied?

**Comment by elserj** [comment]
Not really until we get a webservice built that has the functionality.  So, it is on the roadmap, but not really at this point.

**Comment by jaiswalp** [comment]
I thought the APIs open up by default. In any way we need to bring it up on priority.

**Comment by jaiswalp** [comment]
I meant the APIs

**Comment by elserj** [comment]
Some of the APIs are available, but the ability of autofill is not available yet, from my understanding.  I originally asked Seth about the autofill and he indicated it wasn't really available yet outside of AmiGO, which we are here.  Preece, Chris, Seth and I are actually having a really long email conversation about adding the webservice stuff we want, and have a ticket in geneontology/amigo#292 to hold some of the discussion.

**Comment by preecej** [comment]
The aforementioned long API conversation has now been documented in 
Github amigo issue 292.

Meeting to occur next week.
- j

**Comment by elserj** [comment]
Changed drupal homepage to new search.
