### ISSUE TITLE
google analytics

### ISSUE THREAD

**Issue by jaiswalp** [Planteome/amigo#15]
unless it is in place, can we put the Google  Analytic code integrated.

-pankaj

**Comment by elserj** [comment]
Was already in place for drupal site, added google analytics id to amigo.yaml file and ran "gulp install" for planteome site.  Only done on browser.planteome.org as I don't believe it should be done on dev site, but can change if requested.  Change not made in commit as amigo.yaml is not in repo and id should be obfuscated.
