### ISSUE TITLE
PO links in TO definition source go to plantontology.org

### ISSUE THREAD

**Issue by marieALaporte** [Planteome/amigo#19]
As an example, the PO link in the definition (source) of this TO term goes to the plantontology.org website:
http://dev.planteome.org/amigo/term/TO:0000056

**Comment by elserj** [comment]
@kltm , I thought that if PO was defined in amigo.yaml (in AMIGO_TERM_REGEXP), that this link should stay internal?  Or is the only way to keep this on planteome.org is to change the xref in dbxrefs.yaml?

**Comment by kltm** [comment]
<strike>Well, two ways to do it, with slightly different effects. You'd probably want it in amigo.yaml, with the compiled version making its way to the JS data load.</strike>

<strike>AMIGO_TERM_REGEXP helps trigger the internal/external term effects (different highlighting and blurb, etc.), as well as what category an id falls into in some widgets, like the results table. In other situations, it may do little.</strike>
<strike>That regular expression also shows up in the JS linker, but only for CSS effects, AFAICT. If you have a custom linker, is may work differently.</strike>

**Comment by kltm** [comment]
Okay, my reading comprehension is not what is used to be--my answer was much more related to the dynamic JS bits and the search results table.

For "definition" in the summary section, that is exclusively controlled by db-xrefs.yaml, as this is for the canonical location of the identifier.

One _could_ rewrite the template to redirect locally based on AMIGO_TERM_REGEXP, but that would not be the base behavior for AmiGO.

**Comment by elserj** [comment]
Fixed with commit https://github.com/geneontology/go-site/commit/97bd962e3608e04b315466ff379b79179cc494c6 that changed the dbxref from old PO site to planteome.
