### ISSUE TITLE
Customize look and feel of Planteome AmiGO instance

### ISSUE THREAD

**Issue by cmungall** [Planteome/amigo#2]

**Comment by elserj** [comment]
Mostly done in commits 36e8d1af37a4f37d293419930436c58c8de829d9 3bed73542a81c758e0c40624290eee484b9ba3f8 590b8b68b8402df2bf5640c8445ff737fb736707 27a5dbb5b565b2a2138ef269b0f97c2de54be43c

Probably will be more changes, but these commits hit most of the big changes.  Closing for now and any new changes should be made as separate issues.
