### ISSUE TITLE
Working with ECO and associated annotations

### ISSUE THREAD

**Issue by jaiswalp** [Planteome/amigo#31]
Looking for solutions requested for AmiGO
https://github.com/geneontology/amigo/issues/450

How to associate annotations with ECO terms and search them.

**Comment by elserj** [comment]
Pretty sure this is complete with commit https://github.com/Planteome/amigo/commit/8ac879dbbe60843c228e036677684fbb48936bb3.

Feel free to reopen if anything else needs to be done.
