### ISSUE TITLE
Base_Statistics - add new aspects to "annotations by aspect/species by evidence"

### ISSUE THREAD

**Issue by elserj** [Planteome/amigo#32]
Trying to add non-GO aspects to "base_statistics" graph for annotations by aspect, and it doesn't seem to be as easy as I hoped.

I've modified the javascript/web/BaseStatistics.js file where I think it needs to be, and they show up on the axis, but no annotations are actually picked up.  I assume I need to make some other change to get it to recognize the new aspects, but not sure where it would be.

**Comment by elserj** [comment]
Changes also need to be made to scripts/amigo-create-base-stats-cache.js in the aspect function.

Needs some more testing, I'll update with the commit after.

**Comment by elserj** [comment]
@kltm 
I'm having trouble figuring out how the x-axis elements are chosen.  I can see from the changes I've made on dev (http://dev.planteome.org/amigo/base_statistics#go-annotations-by-aspect-species-by-evidence) that I can get the PO anatomy ones I've loaded to display, but for some reason the cellular component ones for GO don't display.  It appears to be an issue where only so many choices are on display in the x-axis.

Possibly related, but for the "annotations by species" (http://dev.planteome.org/amigo/base_statistics#experimental-annotations-by-species) we had to limit the number of species displayed to 30 (via the "our_species_of_interest" var in amigo-create-stats-cache.js) or the display would not line up properly there either.

I am just guessing, but I don't think the problem is directly in the js, but with however plotly is working on graphing the data.  Thoughts on where to work on this?

**Comment by kltm** [comment]
The JS API is pretty good at plot.ly, if you haven't dived in yet.

From experience, that particular graph is much more "number" oriented, so it will happily drop x-axis labels if they are too dense--you can see them if you zoom in. You can either force the labels, shrink them, etc...
Of course, at that point, you are fighting it, which can cause knock-on issues. Getting the graphs "right" can be a huge time sink. It might be easier to figure out a way to split them and reduce the density.

**Comment by elserj** [comment]
I wrote up a nice long thing explaining that I still had a problem, but it looks like my problem was that IMP and IEA annotations do not show up on that plot.  Guess I can work on figuring out how to add them as a new category of evidence, or should they be included in one of the categories already?  Maybe "genomic context evidence"?

How would I go about adding that?

**Comment by kltm** [comment]
There are a few hard-coded sections in the code that define the categories that are used--you should just be able to add what you need there, assuming that it can be picked up with the closures.

**Comment by elserj** [comment]
I guess I don't see where the closures are defined.  I could be thinking about this all wrong, but I think somewhere there is something that says "author statement" corresponds to "NAS" and "TAS", or something like that, but I'm not finding a file that describes that.

**Comment by elserj** [comment]
Or can I just add something like "automatically assigned" to the "our_evidence_of_interest"?

Tried that, but "automatically assigned" doesn't seem to be right.  Maybe it's just another phrase?  Trying to use what I found on the GO evidence code page.

**Comment by kltm** [comment]
@elserj It must be the exact name used in the (legacy) evidence_type_closure, which is the ECO labels. As for how the GO 3-letter coeds are mapped, for our purposes (as defined in the OWLTools loader in getClassesForGoCode), that currently happens in ECO, where the synonyms have an ECO xref.

**Comment by elserj** [comment]
Thanks.  Got it with "evidence used in automatic assertion"

**Comment by elserj** [comment]
Note, live site will not be changed to reflect this until release is done.  Some data needs to be reloaded for this to happen and probably shouldn't be done on the live site until the release.
