### ISSUE TITLE
Show ontology source (PO, GO, TO) or aspect (T, A, G...) in table for annotations

### ISSUE THREAD

**Issue by elserj** [Planteome/amigo#36]
Per a request from @jaiswalp, show the ontology source/aspect in the annotations table.

I've figured out how to add the aspect letter, which does match the filter, but it isn't clear what each letter represents.

Check http://dev.planteome.org/amigo/search/annotation

Awaiting feedback from @cooperl09 and @jaiswalp.

**Comment by cooperl09** [comment]
I think the letters for the aspects are are ok, they match what's in the filters. Not ideal, but works. 
I think the aspect is more informative than just GO, PO would be
We could provide a table somewhere to the actual names?

**Comment by jaiswalp** [comment]
For viz purposes can you transform the letters to something like
T = Trait
A= anatomy
G= growth
C = Cell part
F = Mol Function
P = Bio Process

**Comment by elserj** [comment]
As I recall, we tried this before, and it wasn't something I could figure out.  I will give it another try, I have an idea how it might be possible.

@kltm, would it be possible to use a yaml file to accomplish this?  Something like the way the rest of the entries on the table use db-xrefs.yaml to build the links?  That seems to be processed after the data is pulled from solr.  Or do you have another idea?

**Comment by kltm** [comment]
@elserj IIRC, if you are talking about the cells in a table, I believe what you're talking about is in conf/handlers.yaml. These list the id of the type to override, the context that is occurs in, and the function to use instead (with the document in question as the argument).

**Comment by elserj** [comment]
This is done for the results table on http://dev.planteome.org/amigo/search/annotation, please let me know if you want the text changed before I close the ticket. I have it as "Trait" and "Anatomy" for now. Another option may be something like "Trait (T)".

After discussion with Seth, this isn't really possible at this time to change in the filter tables.
