### ISSUE TITLE
AmiGO 2: ISBN Xrefs

### ISSUE THREAD

**Issue by jaiswalp** [Planteome/amigo#5]
http://dev.planteome.org/amigo/term/PO:0005849

Suggest directing the ISBN Xrefs to
http://www.isbnsearch.org/isbn/XXXXX

XXXXX replaced by the ISBN ID digits

e.g.
http://www.isbnsearch.org/isbn/0122151704

**Comment by cmungall** [comment]
We definitely want this in the core GO xrefs too

Do you distinguish ISBN10 from 13?

**Comment by cooperl09** [comment]
In the Plant Ontology, we linked all the ISBN#s to this site: http://openisbn.com/
This works for both the 10 and 13 digit numbers.

I suggest we use the same dbxref link, we can update in the GO xref file.

**Comment by jaiswalp** [comment]
http://www.isbnsearch.org/isbn/XXXXX takes both ISBN-10 or -13

**Comment by elserj** [comment]
I think I prefer the openisbn site as it looks less commercial.  It has more info about the actual book rather than just link to where the book can be bought.  Just my two cents.

**Comment by cooperl09** [comment]
Agreed.  See also this page on the PO wiki: http://wiki.plantontology.org/index.php/Refs_ISBN

**Comment by jaiswalp** [comment]
go with it if you all like it..

**Comment by elserj** [comment]
Fixed in geneontology/go-site@e8f74e893ac149dd1ef99d5b758cd4bd6741bc89
