### ISSUE TITLE
Planteome: Ontology GO Alt ID links

### ISSUE THREAD

**Issue by jaiswalp** [Planteome/amigo#6]
http://dev.planteome.org/amigo/search/ontology

GO IDs in the Alt ID column on right link to GO website which does not return anything.

I suggest disabling this hyperlink. There is no need for that link since these IDs are coming from old terms that were merged to the new primary term.

We might have PO terms with Alt ID but did not check it.

**Comment by elserj** [comment]
Closed with upstream merge 0015a68c093d7925265e8387bbe5a770164d6de3
