### ISSUE TITLE
AmiGO 2: Gene Product Xref to external source

### ISSUE THREAD

**Issue by jaiswalp** [Planteome/amigo#9]
http://dev.planteome.org/amigo/gene_product/Ensembl_Plants:OS06G0275000

I think the synonym Ensembl_Plants, OS06G0275000should appear in Database section and hyperlink to external source... Gramene

**Comment by elserj** [comment]
EnsemblPlants already was an xref, but we had mistakenly put in an underscore.  Taking out the underscore does cause these hyperlinks to go out to ensemblgenomes, but not all species we have are there so many return a "no results found" page.  Unless we change from using EnsemblPlants as the db source in the gaf files, not much we can do.

We can change them to something else, but would require a full reload.  Please reopen the ticket if you have a suggestion on a further course of action.
